import React from "react";
import { Link } from "react-router-dom";
const Home = () => {
  return (
    <div className="dhiwise-navigation">
      <h1>Homepage</h1>
      <p className="headline">
        This project was generated By{" "}
        <a href="https://www.dhiwise.com">Dhiwise</a>. Quickly use below links
        to navigate through all pages.
      </p>
      <ul>
        <li>
          <Link to="/">LandingPage</Link>
        </li>
        <li>
          <Link to="/group9hciuidesigntwo">Group9HCIUIDesignTwo</Link>
        </li>
        <li>
          <Link to="/coursesopenpagedesktop">CoursesOpenPageDesktop</Link>
        </li>
        <li>
          <Link to="/group9hciuidesignfour">Group9HCIUIDesignFour</Link>
        </li>
        <li>
          <Link to="/group9hciuidesignfive">Group9HCIUIDesignFive</Link>
        </li>
        <li>
          <Link to="/group9hciuidesignone">Group9HCIUIDesignOne</Link>
        </li>
        <li>
          <Link to="/group9hciuidesignthree">Group9HCIUIDesignThree</Link>
        </li>
      </ul>
    </div>
  );
};
export default Home;
